apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: hello-world-html-content  
  labels:  
    app: {{ .Values.app.name }}  
data:  
  index.html: |  
    <!DOCTYPE html>  
    <html>  
    <head>  
        <title>Hello World</title>  
        <style>  
          body {  
            font-family: Arial, sans-serif;  
            display: flex;  
            justify-content: center;  
            align-items: center;  
            height: 100vh;  
            margin: 0;  
            background-color: #f0f2f5;  
          }  
          .container {  
            text-align: center;  
            padding: 20px;  
            background-color: white;  
            border-radius: 8px;  
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);  
          }  
          h1 {  
            color: #1a73e8;  
          }  
        </style>  
    </head>  
    <body>  
        <div class="container">  
          <h1>Hello World!</h1>  
          <p>Welcome to my Helm-deployed application with Nginx dependency.</p>  
        </div>  
    </body>  
    </html>  